%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Lab 3: Equivalence Class Histograms
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Qiang Qiu 
% qiang.qiu@duke.edu

% Given an arbitrary linear transformation y -> \phi y, the cyclic property 
% of the trace implies that

% w_{a,b}(\phi y) = 1/(2^{m/2} Tr[\phi yy' \phi' D(a,b)]
%                 = 1/(2^{m/2} Tr[yy' \phi' D(a,b)\phi],

% which in turn implies that \phi permutes the Weyl coefficient absolute values 
% if it is an outer automorphism of HW_{2^m}. The outer automorphism group of 
% the Heisenberg-Weyl group is known as the binary symplectic group.


%% Equivalence Class
% Let G be some group of symplectic transformations. We design equivalence 
% classes such that G can only permute the elements of HW_{2^m} within each 
% equivalence class. It follows that the average of the absolute values of 
% the Weyl coefficients within a given equivalence class is invariant under G.


% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Exercise: 
% %%%%%%%%
% Given a vectorized N by N image patch y, taking G to be the group of 
% transformations generated by 90^o rotation, and cyclic horizontal and vertical 
% translation by any multiple of N/4. Design Equivalence classes for G.
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




